### PR TITLE
CV Restyled

### PR DESCRIPTION
**Pull request by jmrplens**
I have redesigned the CV to have some options that I have in my pdf CV.

I'm not too inspired to include more example data, if anyone wants to add data, go ahead.

With my data the CV looks like this: [https://jmrplens.github.io/cv/](https://jmrplens.github.io/cv/ ).
My data: [VIEW FILE](https://github.com/jmrplens/jmrplens.github.io/blob/ce8b5b67dbc5a37dafe9083681b92a6746640b13/_data/cv.yml)

Some screenshots:
Screenshot of Google Chrome (19-4-23, 23-09-51)Screenshot of Google Chrome (19-4-23, 23-10-22)
Screenshot of Google Chrome (19-4-23, 23-10-37)Screenshot of Google Chrome (19-4-23, 23-10-54)

Mobile:

Screenshot of Google Chrome (19-4-23, 23-21-36)Screenshot of Google Chrome (19-4-23, 23-21-48)
Screenshot of Google Chrome (19-4-23, 23-22-00)Screenshot of Google Chrome (19-4-23, 23-22-14)

### CODE REVIEW

**Comment by jmrplens** [comment]
I have a small bug in the markers in the table of contents list.
I'll try to solve it soon, if someone is clear about it, please propose a solution ;)

iPhone 12 screenshot in chrome:
978C8BAC-5A1C-49DB-A14E-A9660FCFE132

**Comment by george-gca** [comment]
LGTM, but I would like opinion from more maintainers. @alshedivat, @pourmand1376, @rohandebsarkar

**Comment by awsaf49** [comment]
@jmrplens thanks for the nice update. I used your code in my site and it looks like this,
image

**Comment by pourmand1376** [comment]
The new design looks good to me. Thank you for your collaboration. 

Let's see what others say.

**Comment by awsaf49** [comment]
@jmrplens anyway to make the table of contents horizontal?? When there are many contents it leaves the right side empty which looks a bit odd. I think having an option for a horizontal table of contents would be nice.

image

**Comment by george-gca** [comment]
@awsaf49 I agree with you. Can you open another issue regarding this matter? If you could also submit a PR would be great.

**Comment by awsaf49** [comment]
@george-gca I will open a issue but not sure about PR as Web Dev is not my expertise. Perhaps @jmrplens  could help...

**Comment by george-gca** [comment]
@awsaf49 I am also not a web dev. But sometimes you can understand how some other things are done on the code and just kind of replicate them elsewhere. Also stackoverflow is really helpful about jekyll liquid stuff.

**Pull request merged**
