### PR TITLE
Update entry_point.sh

### PR DESCRIPTION
**Pull request by pourmand1376**

### CODE REVIEW

**Comment by george-gca** [comment]
Can you check if this fixes it @0xAdriaTorralba?

**Comment by 0xAdriaTorralba** [comment]
> Can you check if this fixes it @0xAdriaTorralba?

Will do ASAP.

**Comment by 0xAdriaTorralba** [comment]
> Can you check if this fixes it @0xAdriaTorralba?

Will do ASAP.

**Comment by 0xAdriaTorralba** [comment]
Tried the fix (reverted to the "old" `Gemfile.lock`) and copied the `entry_point.sh` proposed here and it [fails](https://github.com/0xAdriaTorralba/0xAdriaTorralba.github.io/actions/runs/11032169912/job/30640463715).

**Comment by pourmand1376** [comment]
Thanks for testing it. 

if you want to test it, you have to replace the `docker-compose.yaml` too. This is because the `entry_point.sh` is built into image and will change only when a new image is pushed. 

```
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
```

I think if you revert the Gemfile into the previous version and then commit. After that, you shouldn't have any problems when having local deployments.

**Comment by pourmand1376** [comment]
I merged the change since I'm pretty much sure that line was problematic and I should've changed that since we've added `Gemfile.lock` into repository.

**Comment by george-gca** [comment]
@0xAdriaTorralba can you test again in the same way? Now the docker image have the updated `entry_point.sh`.

**Comment by pourmand1376** [comment]
Yep. Just make sure to pull new image.

**Pull request merged**
