### PR TITLE
Updated Gtag

### PR DESCRIPTION
**Pull request by kakodkar**
Google has released a newer tag for GA.

### CODE REVIEW

**Comment by kakodkar** [comment]
I have tested this for my website and it works.

**Comment by kakodkar** [comment]
You seem to have refactored the code, it'll be great if you can test this out on your version.
Thanks!

**Comment by alshedivat** [comment]
Hi, thanks for pointing this out. I didn't get why you closed this PR. If you don't mind submitting another PR that updates Google Analytics, it'd be very much appreciated. Thanks!

**Comment by kakodkar** [comment]
There was a bug in this one :-D 
Thanks for considering my PRs!

**Pull request closed without merging**
