### PR TITLE
Add jsonresume support

### PR DESCRIPTION
**Pull request by arunoruto**
Just as discussed in #1513 , this pull request adds support for [jsonresume](https://jsonresume.org/). Create the resume once, either as a file in the repository or at [github gist](https://gist.github.com/) called `resume.json`. Put the file in the `_config.yaml`  file and that's it! Other platforms like [resumake](https://latexresu.me/) use the same schema.

I also incorperated the changes introduced by #1339 to the best of my abilites. The style could be further improved.

**Please merge this pull request after #1339 is merged, due to dependencies from it**

If someone has a bettet approach on how to solve the problem that each section needs its own template, please let me know. But for now it works fine and is still backwards compatible with the `cv.yaml` file.

### CODE REVIEW

**Comment by george-gca** [comment]
Nice work! Thanks for this feature.

**Comment by george-gca** [comment]
@arunoruto just now I realized that not all info available in [cv.yml](https://github.com/alshedivat/al-folio/blob/master/_data/cv.yml) was replicated to [resume.json](https://github.com/alshedivat/al-folio/blob/master/assets/json/resume.json). Could you add the missing pieces and also exclude the `cv.yml` file? Or should we keep it as another option? What do you think @pourmand1376?

**Comment by t4rf9** [comment]
It seems the old _data/cv.yml is not working, is it able to have both json and yaml as alternative options? I want the yaml cv back

**Comment by george-gca** [comment]
Afaik the old `_data/cv.yml` is still working. [Here](https://github.com/alshedivat/al-folio/blob/c24ed74855a86d4e67008095ddfe59d08aa8c084/_layouts/cv.html#L5) you can see that we kept it as a fallback if it doesn't find the jsonresume defined.

**Pull request merged**
