### PR TITLE
Badly placed backslash in responsive_img.html

### PR DESCRIPTION
**Pull request by jmrplens**

### CODE REVIEW

**Comment by riohib** [comment]
I am still having issues even after this fix. Github is failing to build my site. I get the following error in my website repo `settings/pages` section:

```
 Your site is having problems building: The tag responsive_image on line 5 in _posts/2015-05-15-images.md is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.
```

**Comment by alshedivat** [comment]
sorry, I'm confused. @jmrplens, what makes this backslash badly placed?

@riohib, are you able to build the website locally? if it works locally, you need to follow https://github.com/alshedivat/al-folio#deployment and setup github actions as described there in order to deploy it to github pages correctly.

**Comment by jmrplens** [comment]
sorry for not putting more explanation.

The backslash is the beginning of the relative path, if the space is not changed it is generated like this:

`srcset=“... /assets/img/me.jpeg 400w, /assets/img/me.jpeg 800w,/ assets/img/me.jpeg ...`

The path for the original size is poorly defined, it does not have the initial backslash

**Comment by jmrplens** [comment]
You can check in your [gh-pages branch (index.html, line 221)](https://github.com/alshedivat/al-folio/blob/a343425ad59b414775f55ff04255c7409b71d784/index.html#L221).

**Comment by riohib** [comment]
@alshedivat Thank you! Changing branch in the pages section in setting from Master to `gh-pages` solved the issue, as mentioned in your docs.

**Comment by alshedivat** [comment]
I tested the suggested fix and it seems to break image loading. correct fix is implemented in 8de1ad4.

**Pull request closed without merging**
