### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by george-gca**

### CODE REVIEW

**Comment by pourmand1376** [comment]
Good fix! 

```
    google-protobuf (4.26.1-aarch64-linux)
      rake (>= 13)
    google-protobuf (4.26.1-x86_64-linux)
      rake (>= 13)
```

Specifying packages like this is very convenient.

**Comment by george-gca** [comment]
Actually `bundler` did all the job. I just did `bundler install` then `bundler update` on my local setup.

**Comment by pourmand1376** [comment]
It's odd that bundler fixed packages for both x86_64 and arm CPUs.

**Comment by george-gca** [comment]
Not really, since you added the second platform in #2396.

**Pull request merged**
