### PR TITLE
adds submenu in navigation bar. (fixes issue #159)

### PR DESCRIPTION
**Pull request by adib2149**

### CODE REVIEW

**Review by alshedivat — CHANGES_REQUESTED** [review]
Looks great! Thanks for your contribution.

Do you mind adjusting the styles a bit to make the dropdown menu more dark mode friendly? Happy to merge after this change.

Screen Shot 2021-07-17 at 9 28 21 AM

**Comment by adib2149** [comment]
My pleasure. I will get back with the requested changes.

**Comment by adib2149** [comment]
I have updated the base scss files for the submenus to work on both dark and light modes. Please check to see whether it works, and let me know in case of any other inconsistencies. Apologies for the delay, I was a bit tied up.

**Review by alshedivat — APPROVED** [review]
Thanks again for adding submenus!

**Pull request merged**
