### PR TITLE
Additional instructions for Apple Silicon Users

### PR DESCRIPTION
**Pull request by 0xAdriaTorralba**
Trying to deal with building the website using Github Actions, I found a problem related to my local development build being an Apple Silicon Mac. 

I found a workaround for this, and I'm sharing and adding the step-by-step to fix the problem, in case you find suitable to include this for the rest of Apple Silicon Mac users :)

### CODE REVIEW

**Comment by george-gca** [comment]
Can you verify this @pourmand1376? I don't have access to a Mac.

**Comment by pourmand1376** [comment]
Hey Guys. 

I tested on mac and I really couldn't figure out the issue. There is no issue here. 

Here's what I've done. 

```
docker compose pull
docker compose up
```

Is there any way to replicate your issue?

**Comment by 0xAdriaTorralba** [comment]
The issue is not related to local development, but when you try to deploy this website to Github Actions, see [here](https://github.com/0xAdriaTorralba/0xAdriaTorralba.github.io/actions/runs/10913865415) an instance of a failed build when you push your changes from local.

Again, local development is just fine using the `docker compose`.

**Comment by george-gca** [comment]
Maybe this is related to #2682, #2544?

**Comment by pourmand1376** [comment]
Can you explain how you updated your Gemfile.lock file and what was the reason?

**Comment by 0xAdriaTorralba** [comment]
> Maybe this is related to #2682, #2544?

Yes, it seems so. I got those issues before updaing the Gemfile.lock

> Can you explain how you updated your Gemfile.lock file and what was the reason?

The way I managed to update the Gemfile.lock is by doing the step-by-step I added on `INSTALL.md`, I paste this again here:

1. Connect to your docker container (`docker exec -it <container_name> sh`)
2. Run the following commands *inside* the container
    ```bash
    bundle lock --add-platform ruby
    bundle lock --add-platform x86_64-linux
    ```
3. Remove Gemfile.lock *outside* the container (`rm -rf Gemfile.lock`)
4. Run `bundle install` *inside* the container.
5. After that, you should have a new `Gemfile.lock` capable of handling builds for both local and production environments.
6. Push the new `Gemfile.lock` and you should be good to go.

The problem here is the following: the first time you run `docker compose pull; docker compose up` it is populated using the LOCAL development environment, so, it lists and adds the proper items to Gemfile.lock for THAT (local) platform (in my case, ARM-based ones). HOWEVER, it may be the case that the PRODUCTION environment architecture is DIFFERENT from your local one (this is my case, and also the cases on issues #2682, #2554). In this case, you need to rebundle the Gemfile.lock to consider this platform target. Is it clear now?

**Comment by george-gca** [comment]
Somehow its Gemfile.lock is apparently being overwritten and commited to the repo, which I believe it shouldn't. We have [Gemfile.lock](https://github.com/alshedivat/al-folio/blob/master/Gemfile.lock) versioned here and also [added to the .gitignore](https://github.com/alshedivat/al-folio/blob/046545983f0864b62e883105955717cbf298561c/.gitignore#L9). Also if you look at the versioned Gemfile.lock we have

https://github.com/alshedivat/al-folio/blob/046545983f0864b62e883105955717cbf298561c/Gemfile.lock#L215

which is the version you just locked into.

**Comment by pourmand1376** [comment]
@0xAdriaTorralba 

OK. Thanks for explanation. I think a better workaround is that you don't commit `Gemfile.lock` to the repository and it remains the same instead of changing it everytime. Does that solve your problem?

For that before any commit do this:
```
git restore Gemfile.lock
```

@george-gca And About `.gitignore`. Adding a file to gitignore won't work if we already have that file tracked in repository.

**Comment by pourmand1376** [comment]
Thanks for mentioning that. I think we need to add another PR or change this PR somehow to make that change everytime. 

We should add this command somewhere to be run after finishing local deployment:
```
git restore Gemfile.lock
```

**Comment by george-gca** [comment]
Maybe we should do [something](https://stackoverflow.com/a/13631525) like `git update-index --assume-unchanged` somewhere? Idk if it would solve the issue, since this flag can't be pushed to the repo.

**Comment by pourmand1376** [comment]
I merged the change since I'm sure that line was problematic and I should've changed that since we've added `Gemfile.lock` into repository.

**Comment by pourmand1376** [comment]
I merged my change. It should solve this problem.

**Comment by pourmand1376** [comment]
This is not needed anymore.

**Pull request closed without merging**
