### PR TITLE
add sticky toc

### PR DESCRIPTION
**Pull request by eolesinski**
This PR adds a sticky toc to the Distill template as mentioned in #1961

Changes:
- adds sticky toc
- reduces separator line width (for better fit)

### CODE REVIEW

**Comment by alshedivat** [comment]
thanks for adding this feature. the only issue I noticed is that transparent background of the sticky toc doesn't look good when the toc bloc starts overlapping with other objects on the page. also, this won't work on mobile well. could you think of a way to fix these issues?

|Screenshot 2024-05-27 at 1 01 07 PM|Screenshot 2024-05-27 at 1 00 27 PM|
|---|---|

**Review by alshedivat — CHANGES_REQUESTED** [review]
see above comment about the stylistic issues. these need to be fixed before we can merge this PR. thank you.

**Comment by eolesinski** [comment]
@alshedivat great point - thanks for the feedback. I'll take a look.

**Comment by george-gca** [comment]
How did you envision this collapsible toc in this case? Where and how it would appear on mobile? I tend to think that just hiding the toc would be a good use, since the mobile screen is too small to fit both the toc and the contents.

**Comment by hrhoo** [comment]
I had a look at the changes.

How about adding this line.
image

When the window is small, it makes the toc fixed

**Comment by saguileran** [comment]
Is there any possible and easy solution?

**Comment by george-gca** [comment]
@hrhoo can you test if your solution works, and if so, send a PR with this?

**Pull request closed without merging**
