### PR TITLE
Added anchor to category sections

### PR DESCRIPTION
**Pull request by fabawi**
Added anchor to categories so one could navigate to the category section from the URL:

e.g.,

https://alshedivat.github.io/al-folio/projects#fun

### CODE REVIEW

**Review by george-gca — COMMENTED** [review]
Based on this, I believe we should also have links for them.

**Comment by alshedivat** [comment]
@fabawi, I agree with @george-gca. could you add a `href` attribute with a link to the category page? I'll go ahead and merge after that.

**Comment by fabawi** [comment]
@george-gca @alshedivat I added the header to the anchor link. Doing it the other way around (link inside header) is cleaner, but changes the look of the header, so I went with the former. Now when you click on the category's header it navigates to the page anchor

**Comment by george-gca** [comment]
@fabawi can you update this PR so we can merge it?

**Comment by fabawi** [comment]
@george-gca updated

**Pull request merged**
