### PR TITLE
Fix distill darkmode

### PR DESCRIPTION
**Pull request by ivanpuhachov**
Fixing the issue with distill darkmode #298

I found out that the problem emerges with numerated lists, table entries, inline math equations, blockquotes (see also #280 ), footnotes, citations, hovering boxes and code highlights. Seems to be fixed now, take a look on `al-folio/blog/2021/distill/` when building locally, or online on my page: [here](https://puhachov.xyz/blog/2018/distill/)

Let me know if something is missing. Cheers!

### CODE REVIEW

**Comment by alshedivat** [comment]
Thanks so much for fixes!

**Comment by ivanpuhachov** [comment]
Fixes #298 

(comment to link pr to issue)

**Comment by alshedivat** [comment]
@ivanpuhachov, just realized you made changes to `assets/js/distillpub/template.v2.js`. Thanks for taking the effort!

I'm wondering, would it be hard to factor out these style changes into `_sass/_distill.scss` instead of directly editing the `template.v2.js`? The reason is that `template.v2.js` is currently auto-generated from the [al-folio branch of my fork of distillpub template](https://github.com/alshedivat/distillpub-template/tree/al-folio) (later, I'm thinking of switching to loading `template.v2.js` directly from https://distill.pub/template.v2.js). So, I'd strongly prefer treating `template.v2.js` as read-only and make changes by overriding functionality.

**Comment by ivanpuhachov** [comment]
The problem is that `template.v2.js` automatically generates `style` properties for created items and stores them right in the cell (see, i.e. line 1374 in `template.v2.js`). I tried to override them with scss file and `!important` flag but I did not succeed. Is there another method to do so? I can try

**Comment by alshedivat** [comment]
You are right, it looks like most of distill is written using web components that encapsulate styles using shadow DOM. The styles inside shadow DOM cannot be overridden from outside using CSS, unfortunately (see [discussion here](https://stackoverflow.com/questions/37352637/shadow-dom-styling-from-the-outside)). But, these styles can be overridden using javascript without directly modifying `template.v2.js`.

I added `assets/js/distillpub/overrides.js` that overrides `d-footnote` and `d-cite` styles. Would you mind reverting your changes in `template.v2.js` and using this method instead?

**Comment by ivanpuhachov** [comment]
Great. Will do!

**Comment by ivanpuhachov** [comment]
Done!

**Review by alshedivat — APPROVED** [review]

**Pull request merged**
