### PR TITLE
Adds support `max_author_limit`

### PR DESCRIPTION
**Pull request by rohandebsarkar**
As requested in #701.

### CODE REVIEW

**Review by alshedivat — COMMENTED** [review]
could you add an example bib item that demonstrates `max_author_limit`?

**Comment by rohandebsarkar** [comment]
In the hover, if there are more than tree authors, the authors are not distinguishable with one another. Will it be better to add a semicolon or an “and” and the end of all authors?

**Review by alshedivat — APPROVED** [review]
LGTM. added some minor improvements. feel free to merge if looks good.

**Comment by Randl** [comment]
Thanks for the feature implementation!

I'd like to note that rendering of the full list is pretty slow for me for large amount of authors -- you can see it here https://evgeniizh.com/publications/

Also it would be nice if expanded list was formatted as the regular one and not with dashed underlining.

**Comment by alshedivat** [comment]
@Randl, "428 more authors"... damn! 😄

- to speed up rendering, feel free to reduce the delay between rendering characters by editing line 115 of `_layouts/bib.html` and changing 15 ms to something like 0.1 ms, which should speed up rendering for you >100x.

- feel free to adjust the styling of the additional authors however you want by editing `_sass/_base.scss` lines 522-530.

hope this helps!

**Pull request merged**
