### PR TITLE
Added support for jupyter notebooks #417

### PR DESCRIPTION
**Pull request by george-gca**
Implemented #417. Just don't know if everything that I need to run the code was added correctly in the `Dockerfile`. What is the best way for me to check for this?

### CODE REVIEW

**Comment by george-gca** [comment]
Currently failing because it couldn't find `jupyter` command in docker image. How can we add jupyter to it? I believe it doesn't use the `Dockerfile` contained in the repo to create the image used.

**Comment by george-gca** [comment]
@pourmand1376 can you add `jupyter` dependency to the docker image? I believe `apt install python3-jupyter-core` is enough.

**Comment by pourmand1376** [comment]
> @pourmand1376 can you add `jupyter` dependency to the docker image? I believe `apt install python3-jupyter-core` is enough.

Have you tested this solution on your local docker?

**Comment by george-gca** [comment]
I re-run the build check and it failed again.

The `Dockerfile` was updated, but not the docker image in the docker hub. If you check the image layers for the [latest tag](https://hub.docker.com/r/amirpourmand/al-folio/tags), you'll see that the `apt-get` lines are still the same.

**Comment by pourmand1376** [comment]
Deploy will fail because you haven't added `jupyter` to github action. I do not know how to do this. 

Dockerhub image will update after we merge this request. In order to test it, use:
```
docker compose -f docker-local.yml up
```
and you will see that it builds an image and deploy the website locally.

**Comment by george-gca** [comment]
Just realized that the GitHub action doesn't use your docker image. I always presumed it did.

Looking into [.github/workflows/deploy.yml](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml) I saw this line `runs-on: ubuntu-latest`. After doing some digging, found that this image comes from [here](https://github.com/actions/runner-images), and it already has [these tools](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) installed. Added [step to install jupyter there](https://github.com/alshedivat/al-folio/pull/1511/commits/7e50922f2cb7bbfba0bc22b28e2fc5d580633595) and apparently everything runned smoothly.

**Comment by george-gca** [comment]
Just managed to test in a docker environment and it worked like a charm. Merging it into main.

**Comment by lonzoweb** [comment]
I'm trying to delpoy in netlify but getting similar jupyter errors, added jekyll-jupter to gemfile and plugins but still getting: 

Missing dependency: jupyter

any ideas?

**Comment by george-gca** [comment]
Do you have permission to install things outside ruby? If so, you are missing jupyter installation. Install it via `pip3 install jupyter`

**Pull request merged**
