### PR TITLE
Add Reload to Docker (Automatic Reload of Changes to _config.yaml)

### PR DESCRIPTION
**Pull request by pourmand1376**
- #1640

### CODE REVIEW

**Comment by george-gca** [comment]
I will give it a test in the weekend.

**Comment by alshedivat** [comment]
very useful feature, thanks for adding it! defer to you guys for testing the changes and merging once ready.

**Comment by george-gca** [comment]
@pourmand1376 what is the best way for me to test these changes? I mean, to apply all the commits and test? I want to apply these in a remote pc where I have docker installed, but I don't have github cli there.

**Comment by pourmand1376** [comment]
> @pourmand1376 what is the best way for me to test these changes? I mean, to apply all the commits and test? I want to apply these in a remote pc where I have docker installed, but I don't have github cli there.

Hi.
First clone the repo. 
```
git clone https://github.com/alshedivat/al-folio/
```
Then switch to `add-notify-docker`
```
git switch add-notify-docker
or 
git checkout -b add-notify-docker
```
Then do `docker compose up --build`.

**Comment by TimChild** [comment]
In case it is helpful to you, I just tried following 

> ```
> git clone https://github.com/alshedivat/al-folio/
> ```
> 
> Then switch to `add-notify-docker`
> 
> ```
> git switch add-notify-docker
> or 
> git checkout -b add-notify-docker
> ```
> 
> Then do `docker compose up --build`.

But, when I do that, I get the following error:
```
al-folio-jekyll-1  | exec ./bin/entry_point.sh: no such file or directory
al-folio-jekyll-1 exited with code 1
```

This is running on a Windows 10 PC, Docker version 24.0.6, using the WSL 2 based engine. 

The reason I was trying this is that I have the same issue that others report where the only way to see updates in the locally served site is to re-build the docker container.

**Comment by curtisjhu** [comment]
Yes the master branch contains breaking changes. It doesn't work if you just try to git clone and run `docker compose up` like the readme says.

You get the same error as from above.
```
al-folio-jekyll-1  | exec ./bin/entry_point.sh: no such file or directory
al-folio-jekyll-1 exited with code 1
```

**Comment by curtisjhu** [comment]
I suppose we need to wait to update base docker image. Good thing the PR is being viewed.

**Comment by pourmand1376** [comment]
> Yes the master branch contains breaking changes. It doesn't work if you just try to git clone and run `docker compose up` like the readme says.
> 
> You get the same error as from above.
> 
> ```
> al-folio-jekyll-1  | exec ./bin/entry_point.sh: no such file or directory
> al-folio-jekyll-1 exited with code 1
> ```

The problem should be solved. You should pull a new docker image version to see the effect.

**Pull request merged**
