### PR TITLE
update academicons to 1.9.4

### PR DESCRIPTION
**Pull request by TheFermi0n**
This addresses the #1704 issue. 

I have changed the following,

- changed academmhcons from cdn to local installation (v1.9.4)
- added the arXiv social which uses the new icon as required in #1704

### CODE REVIEW

**Comment by alshedivat** [comment]
I suggest rebasing this on top of #1562, testing, and merging it after #1562 lands.

**Comment by TheFermi0n** [comment]
> I suggest rebasing this on top of #1562, testing, and merging it after #1562 lands.

Okay, I did something. No idea if I did it correctly. But something is done. Please let me know if I messed up. Thank you

**Comment by TheFermi0n** [comment]
Wow, this actually improved [my website's](https://thefermi0n.github.io) pagespeed score. You can check the [score here](https://pagespeed.web.dev/analysis/https-thefermi0n-github-io/7uczphp5ff?form_factor=mobile).

**Comment by george-gca** [comment]
Sorry, I am quite in a busy couple of weeks. I can take a look at it, but not until weekend of next week

**Comment by george-gca** [comment]
I believe this is now fixed since academicons 1.9.4 was already added in #1562. @TheFermi0n can you check if this is still needed?

**Comment by TheFermi0n** [comment]
> if this is still needed?

Sorry for the late response. No, I don't think this is still needed. I am closing this pull request. Thank you.

**Pull request closed without merging**
