### PR TITLE
fix: search_enabled -> bib_search

### PR DESCRIPTION
**Pull request by CheariX**
In #2523, I did a copy&paste error with https://github.com/alshedivat/al-folio/commit/07d6e619cced7a2256bbe6de582ad68f93cd1553

I used the global `search_enabled` config key instead of the correct `bib_search` key.

This PR fixed it.

### CODE REVIEW

**Comment by george-gca** [comment]
I think it would be better to move the include of the script from [_includes/scripts/misc.liquid](https://github.com/alshedivat/al-folio/blob/master/_includes/scripts/misc.liquid) to the [publications page](https://github.com/alshedivat/al-folio/blob/master/_pages/publications.md), since only that page uses `bibsearch.js` and currently it is being included in all pages as long as the config is set to use it.

**Comment by CheariX** [comment]
Hm. Good point. In my personal setup, I use the bibsearch box on many pages. So it made sense to include it in `misc.liquid`. But most people maybe only have a single bib page.

**Comment by george-gca** [comment]
Maybe you could change for the template, and keep it as is in your personal site since it makes sense.

**Comment by CheariX** [comment]
Sure. I think, this makes sense for most people.

**Comment by george-gca** [comment]
> An alternative would be create a file in. include/bibsearch.liquid and include it. This would allow other people to easily integrate it. What do you think?

I like this idea most, makes sense.

**Comment by CheariX** [comment]
Done.

(I had some Git hiccups, but I think I could solve it with a force push. )

**Review by george-gca — APPROVED** [review]

**Comment by george-gca** [comment]
Thanks for the changes. Just out of curiosity, how are you using this search in other parts of your site? I mean, what code changes should you made to reuse this somewhere?

**Comment by CheariX** [comment]
I manage a lot of content on my site using BibTeX for bibliography management. For example, I list my teaching courses, supervised theses, and press articles. 

I found this to be the easiest method since I use Zotero to manage my papers, theses, and other resources anyway, and Zotero has a great auto-export to BibTeX feature (Better BibTeX extension).

**Pull request merged**
