### PR TITLE
Add .lycheeignore file with linkedin to stop error on workflow Linkcheck

### PR DESCRIPTION
**Pull request by Eyezuhk**
Add a .lycheeignore file with LinkedIn to stop the error in the workflow Link Checker due to response 999, and update to the new version lycheeverse/lychee-action@v2.1.0.

### CODE REVIEW

**Review by george-gca — APPROVED** [review]

**Comment by george-gca** [comment]
Can you also add reddit to the `.lycheeignore` file? It is currently throwing an error because of it. Also ignore the prettier error.

**Comment by Eyezuhk** [comment]
reddit.com added to .lycheeignore  file ^^

**Comment by george-gca** [comment]
Is it still a draft or is it ready?

**Comment by Eyezuhk** [comment]
It's ready.

**Comment by george-gca** [comment]
Thanks for your contribution.

**Pull request merged**
