### PR TITLE
social: add work url

### PR DESCRIPTION
**Pull request by junghans**
Allow email to be empty - for spam protection and add entry for work homepage.

### CODE REVIEW

**Comment by junghans** [comment]
Hmm, `—dry-run` was passed correctly not sure why it still trying to push.....

**Comment by alshedivat** [comment]
Hmm, strange, maybe you could just locally try `git push --dry-run` to reproduce the error?

**Comment by junghans** [comment]
Reading https://groups.google.com/u/1/g/repo-discuss/c/g5iz84EbSz4, it seems `--dry-run` is happening after the authentication and external PR, of course, by design have no permissions on the repo.

**Review by alshedivat — APPROVED** [review]
LGTM

**Pull request merged**
