### PR TITLE
Fix titles and headings

### PR DESCRIPTION
**Pull request by rogerthat94**
The If statements to decide the page title and header seemed incorrect. This fixes these.

### CODE REVIEW

**Comment by alshedivat** [comment]
Thanks for the contribution. Which exact issue does this PR fix?

**Comment by rogerthat94** [comment]
`{{ site.title }}` was never getting used as the title and heading. The condition `if site.title == blank` was never true, because blank was not in quotes. In addition, {{ site.title }} is the wrong value to use in this case. 

To see the problem, try using the theme with title set as blank.

**Comment by alshedivat** [comment]
@rogerthat94, thanks for pointing this out. Looks like the bug was introduced in [this commit](https://github.com/alshedivat/al-folio/commit/619bb2df74a79d551785d3c478fb7cc6fe2c028d). If that's the case, then `_layouts/about.html` probably has the same issue. Could you please confirm that?

On a stylistic note, how about we switch from `{% if site.title == "blank" %}` to just `{% if site.title %}` and flip the true and false branches? I just find it weird that liquid evaluates `"" == "blank"` to true.

And thanks again for spotting this!

**Comment by rogerthat94** [comment]
We don't want to look for site.title being undefined. We want to check if it's specifically the string "blank"

See https://github.com/alshedivat/al-folio/blob/9229f7d881d215969378fdc287fdad51936037f9/_config.yml#L5

If you'd rather check `{% if site.title %}`, we should change _config.yml to comment out the title and say "the website title (if undefined, full name will be used instead)"

**Pull request merged**
