### PR TITLE
Enable custom SVG as social icon

### PR DESCRIPTION
**Pull request by scottleechua**
Addresses Issue #2268: Add IETF social integration.

The social integration aspect is straightforward, but [as mentioned](https://github.com/alshedivat/al-folio/issues/2268#issuecomment-2053612898) in the original issue, adding this feature introduces the **use of SVGs as social icons**.

## Current approach
Seeking wider input on how we want to handle SVG social icons. 

In this PR, I made a new social entry `ietf_id` that would show up like this:

Screenshot 2024-07-11 at 10 31 29

I enforced an SVG height of `4rem` to match the styling on the font icons.

It's possible to style the SVG further to match the appearance with the font icons (e.g., enforce monochrome, remove wordmark), but personally I think it wouldn't look as nice.

## Possible Alternative Approach
A possible alternative is to take this as an opportunity to create a more general `svg` entry under social integrations in `_config.yml`, for users to bring their own SVGs. Something like:

```
svg:
  logo: _includes/svg/<LOGO>.svg
  link: https://website.com/profile
```

Then styling would be up to the user.

### CODE REVIEW

**Comment by george-gca** [comment]
I don't think I like the idea. The point of using as a font is to make sure the styling of the icons are the same, considering colors, size, etc. If I change the font color in css I would expect to all icons change their color. Also I don't know if I would add this to our `_config.yml`, but currently I have no other suggestion.

I am considering starting a fork of academicons to give support for this kind of issue (since it is being over a year that they made any changes), but I am not sure how hard it is to do this.

**Comment by scottleechua** [comment]
I agree that a font-based solution would absolutely be the best case, yes. I wonder if it's worth reaching out to the owner of Academicons to see what his plans are for the repo. I personally don't mind maintaining it, and would be willing to reach out. What do you think?

**Comment by george-gca** [comment]
I doesn't hurt to try. There are many open requests for icons there, and the last update to the repo was over a year ago.

**Comment by george-gca** [comment]
But I don't think we should close the issue just yet. Maybe we can think of a better way for someone to insert their svgs, maybe a guideline of how it should be, idk.

**Comment by scottleechua** [comment]
I'm also on the fence about this. I think the most helpful guiderail this provides is enforcing the SVG height to be the same as the other social icons. Happy to leave this open so other users with a stake can share their thoughts. 😄

**Comment by scottleechua** [comment]
I've reached out to the Academicons folks for a chat at the end of the month, and will update here on the outcome of that conversation. 👌

**Pull request closed without merging**
