### PR TITLE
Upate docker-compose to be easier to use for permission bug

### PR DESCRIPTION
**Pull request by pourmand1376**
Hey @george-gca ,

I am thinking about what you've done in `docker-compose.yaml`. 

Does it solve the problem if we just do this change in docker-compose?

- https://stackoverflow.com/questions/48727548/how-to-configure-docker-compose-yml-to-up-a-container-as-root

### CODE REVIEW

**Comment by george-gca** [comment]
Sorry for the huge delay. I'll take a look at it.

**Comment by george-gca** [comment]
No, it doesn't. Same error:

```
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:181:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 (Errno::EACCES)
```

**Comment by pourmand1376** [comment]
How can I replicate this?

**Comment by george-gca** [comment]
Tbh I have no idea. I tried to use it on my laboratory server, where we use docker to run experiments. The docker installation there have some restrictions, to avoid someone being able to run code inside docker as root. And I have no idea how they did this.

**Pull request closed without merging**
