### PR TITLE
Including Lattes Curriculum in Socials

### PR DESCRIPTION
**Pull request by damascenodiego**
The Lattes Curriculum is the Brazilian Standard database of academic records of publications [[1]]. 
This is the de facto source of information about individual researchers and Brazilian institutions [[2]].
All researchers and institutions are required to maintain their records up to date. The platform can be used to obtain information on individual researchers and also to conduct performance evaluations at the organizational level [[3]].

This patch would be an excellent addition to the Brazilian academic community and researchers closely collaborating with Brazilian research institutions.

[1]: https://lattes.cnpq.br/
[2]: http://www.ppgpatologia.ufc.br/index.php/en/student-support/lattes-curriculum-guidelines
[3]: https://en.wikipedia.org/wiki/Lattes_Platform#cite_note-2

### CODE REVIEW

**Comment by george-gca** [comment]
I am brazilian and I added lattes to my personal repo, but never submitted a PR with it. At that time I thought that this would not be useful to a more broader community. But since the changes needed for that are so small, I believe yes, they would fit the purpose of the template.

**Comment by george-gca** [comment]
Just one small question @damascenodiego, what exactly does the `fa-fw` class add to the lattes icon? In my solution I did not use it, and I can't perceive any visual difference.

**Comment by damascenodiego** [comment]
My bad. That is a fontawesome class to set a fixed width to a list of icons.
You can remove that.

**Comment by damascenodiego** [comment]
@george-gca I did a mess with my fork and had to setup my website from scratch.
The current version has a new branch with a similar patch, but the `fa-fw` issue discussed above.
The branch is at https://github.com/damascenodiego/damascenodiego.github.io/tree/patch-1

How should we proceed to have this pull request added? do you want me to add another pull request? 
Or would you prefer to reopen this and remove the `fa-fw` manually?

**Comment by george-gca** [comment]
Which one is easier for you, as long as the commits are like the ones here.

**Comment by damascenodiego** [comment]
Done in #1404

**Pull request closed without merging**
