### PR TITLE
Added/Improved Formatting for Checkboxes

### PR DESCRIPTION
**Pull request by DavidKrassnig**
A proposed solution for #2190. Padding is added such that I considered it aesthetically pleasing and the bullet points in front of the check marks were removed.

### CODE REVIEW

**Comment by DavidKrassnig** [comment]
**Prettier Check:** Not sure what to do here. The scss-file doesn't appear to be prettier-compliant from the get go (at least when I run prettier on it, it changes). The parts that I specifically added to it ought to be prettier-compliant, however, as I ran prettier on it and then only added my new part via `git add -p`. The example post md-file also isn't prettier-compliant and I just went along with its style.

Let me know what (if anything) I should change here.

**Comment by DavidKrassnig** [comment]
**Help wanted:** Ideally, I'd like the check boxes to render in the global theme colour but whenever I specify it, it doesn't appear to change anything. Happy for any pointers by people more knowledgable than I in this area.

**Comment by george-gca** [comment]
Nice work. About the checkbox, I found [this answer](https://surveyjs.answerdesk.io/ticket/details/t10662/changing-color-of-disabled-checked-checkboxes). The thing is, the checkbox is both disabled and checked.

As for prettier formatting, when the workflow fails it generates an html artifact where you can see the diff. Check it [here](https://github.com/alshedivat/al-folio/actions/runs/7886000703).

**Comment by DavidKrassnig** [comment]
> As for prettier formatting, when the workflow fails it generates an html artifact where you can see the diff. Check it [here](https://github.com/alshedivat/al-folio/actions/runs/7886000703).

Thanks, fixed it.

> Nice work. About the checkbox, I found [this answer](https://surveyjs.answerdesk.io/ticket/details/t10662/changing-color-of-disabled-checked-checkboxes). The thing is, the checkbox is both disabled and checked, so maybe it is not possible to change its color so easily (even though they state that it should be possible to change anything with css).

Hm, thanks for the source. Oh, well, perhaps I'll manage at some other point in time. It's not really crucial.

**Comment by DavidKrassnig** [comment]
> @DavidKrassnig can you do the changes I requested?

I'm sorry, what requested changes? I only see (i) your link that delved further into why getting the colours to change is probably not possible and (ii) the remark about prettier code (which I already implemented).

If you are talking about this snippet from your link, then that one doesn't mesh well with Al-Folio's light theme.

```
input[type="checkbox"][disabled][checked] {
  filter: invert(100%) hue-rotate(18deg) brightness(5);
}
input[type="checkbox"][disabled] {
  filter: invert(100%) hue-rotate(18deg) brightness(5);
}
```

See this result:

**Comment by george-gca** [comment]
Yes, idk why sometimes people don't see my reviews. I don't know how GitHub displays (or not) them, so I tried to change it on your branch directly, but obviously failed haha.

image

**Comment by DavidKrassnig** [comment]
> Yes, idk why sometimes people don't see my reviews. I don't know how GitHub displays (or not) them, so I tried to change it on your branch directly, but obviously failed haha.

Oh, yeah, I didn't/don't see that review. Did you submit it? (it shows as _Pending_ on your screenshot)

**Comment by george-gca** [comment]
Now I get it, I forgot to set request changes and apply. My mistake.

Can you fix the prettier and the other issue? Weirdly enough, the broken link is in a file you didn't change.

**Comment by george-gca** [comment]
Forget about the broken links action, I will fix this later. As for the prettier one, probably the citation should be in one line.

**Comment by DavidKrassnig** [comment]
Btw, you can just squash the PR into one co-authored commit if you'd like. No reason for this messy stuff to become immortalized in the main line :joy:

**Comment by george-gca** [comment]
I always squash the commits, trying to keep the base clean.

**Pull request merged**
