### PR TITLE
Added support for a newsletter

### PR DESCRIPTION
**Pull request by asboyer**
In reference to idea: https://github.com/alshedivat/al-folio/discussions/2097
In reference to request: https://github.com/alshedivat/al-folio/issues/923#issuecomment-2171924663

Added support to integrate a [loops.so](https://loops.so/) mailing list into the site.

To use, you need to enable `newsletter` in `_config.yml`. You also must specify a loops endpoint (although I think any mailing list endpoint can work), which you can get when you set up a mailing list on loops. More documentation on loops: [here](https://loops.so/docs/forms/custom-form).

Once that is enabled, the behavior is different depending on how you specified your footer to behave in `_config.yml`. If `footer_fixed: true`, then the sign up will appear at the bottom of the about page, as well as at the bottom of blog posts, if you enable `related_posts`.

If `footer_fixed: false`, then the newsletter signup will be in the footer (on every page), like it is in on [my website](https://asboyer.com).

I'm not attached to the placement of the signup, and you can choose to include it wherever you want with `{% include scripts/newsletter.liquid %}`. Also if you include positional variables into that, you can choose how you center the signup. So `{% include scripts/newsletter.liquid left=true %}` positions the signup bar to the left.

Here are some screenshots below:
## Dark version
image

## Light version
image
I think the input field color should probably change to maybe be light for both themes? What do you think? I think the dark background looks cool, but I don't usually see that done like that on other sites.

## Footer fixed
image

image

## Footer not fixed
image

image
To clarify, if footer isn't fixed, the email signup will appear on every page.

### CODE REVIEW

**Comment by asboyer** [comment]
Also, can someone mark this as an enhancement/feature? I don't think I have the ability to tag this PR as anything.

**Comment by george-gca** [comment]
This looks really nice. As for the background of the light version, I believe it is best to set to white for readability, or maybe a light gray as long at it doesn't look like a disabled element.

**Comment by asboyer** [comment]
Okay, this is how it looks like in light mode now:

#### Dormant
image

#### Active
image

**Review by george-gca — APPROVED** [review]

**Comment by george-gca** [comment]
@asboyer I merged your commit, but just now realized that we forgot about adding this to our README. Would you mind sending a new PR with an explanation added to [CUSTOMIZE.md](https://github.com/alshedivat/al-folio/blob/master/CUSTOMIZE.md)?

**Comment by asboyer** [comment]
> @asboyer I merged your commit, but just now realized that we forgot about adding this to our README. Would you mind sending a new PR with an explanation added to [CUSTOMIZE.md](https://github.com/alshedivat/al-folio/blob/master/CUSTOMIZE.md)?

Yes, I'll whip that up now.

**Pull request merged**
