### PR TITLE
 Issue 105 : Dark Mode + Theming #118 

### PR DESCRIPTION
**Pull request by Jongwoo-Shim**
Created separate branch for dark mode, as I maybe submitting another PR.

### CODE REVIEW

**Review by alshedivat — CHANGES_REQUESTED** [review]
Thanks for your contribution! Looks great, especially the theming feature.

One request before I merge: could you make the dark mode an optional feature (off by default)?
To do that, simply add a variable to `_config.yml` called `enable_dark_mode` (similar to [other optional features](https://github.com/alshedivat/al-folio/blob/master/_config.yml#L146-L154)) and make sure that dark-mode specific code is loaded only when `enable_dark_mode=true`.

**Comment by Jongwoo-Shim** [comment]
Sounds good I'll make the change by Wednesday latest.

**Comment by Jongwoo-Shim** [comment]
Made the requested change. If you require a rebased version I can make another pull request using the master branch : https://github.com/Jongwoo-Shim/al-folio/tree/master

**Review by alshedivat — APPROVED** [review]
Great, thanks for making the changes!

**Pull request merged**
