### PR TITLE
Update Base Docker Image

### PR DESCRIPTION
**Pull request by pourmand1376**

### CODE REVIEW

**Review by alshedivat — APPROVED** [review]

**Comment by george-gca** [comment]
Question, why change this for the 23.10? The `latest` tag is automatically set for the latest LTS release, which currently is 22.04. The next LTS release will be 24.04 I believe.

**Comment by pourmand1376** [comment]
You're right. I thought this would help to solve the windows docker issue. But it didn't.

**Comment by george-gca** [comment]
> You're right. I thought this would help to solve the windows docker issue. But it didn't.

Have you added the mermaid dependency? But nevermind, today I will try to work on #1609 that maybe will also fix this, since most errors with Windows are related to the post with mermaid diagrams.

**Comment by alshedivat** [comment]
should we close this one?

**Comment by pourmand1376** [comment]
Yeah.

**Pull request closed without merging**
