### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by pourmand1376**

### CODE REVIEW

**Comment by pourmand1376** [comment]
We should push new image version for docker-compose changes to take affect.

**Review by george-gca — APPROVED** [review]

**Comment by george-gca** [comment]
Sorry, I missed that in the merge.

**Comment by pourmand1376** [comment]
We should've released a version before merging this. 

But no problem can you do it now?

**Comment by george-gca** [comment]
I can't, only @alshedivat can.

**Pull request merged**
