### PR TITLE
Added support to PurgeCSS

### PR DESCRIPTION
**Pull request by george-gca**
Tackled #1329 with [PurgeCSS](https://purgecss.com/).

Being talking with @varuniyer about using [jekyll-uncss](https://github.com/episource/jekyll-uncss) to reduce css file sizes by ditching unused classes. This approach have 3 main problems:

1 - have some limitations as pointed [here](https://github.com/alshedivat/al-folio/issues/1329#issuecomment-1546517327)
2 - last update to [jekyll-uncss](https://github.com/episource/jekyll-uncss) was about 3 years ago, so it might have a few issues
3 - [uncss](https://github.com/uncss/uncss) haven't seem a new release in a while, currently [lacking maintenance](https://github.com/uncss/uncss/issues/459), and using some deprecated libraries as seem here:

```
npm install -g uncss
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

I thought about giving PurgeCSS a go, since it has been more [actively maintaned](https://github.com/FullHuman/purgecss), but [jekyll-purgecss](https://github.com/mhanberg/jekyll-purgecss) haven't.

For this, I needed to change to use some local libraries instead of getting them via CDN. The good news is that it is quite effective in reducing css file sizes. Comparing dir sizes with `du -hs _site/assets/css/`:

| current | minify | PurgeCSS | PurgeCSS + minify |
| ------- | ------ | -------- | ----------------- |
| 1,1M    | 988K   | 456K     | 420K              |

### CODE REVIEW

**Comment by pourmand1376** [comment]
It would be a lot better if we could see the online version of the site after the pull request without building it locally. Is it possible for Jekyll? @rohandebsarkar

**Comment by george-gca** [comment]
For this specific case I can use these commits in [my demo site](https://george-gca.github.io/multi-language-al-folio/) and we can check if everything is ok there. What do you think?

Another solution is to create an install script to install everything needed to run locally outside of docker, so you could test it. But I agree, see an online version after each PR (or at least select the PRs to which generate a temporary demo from) would be better.

**Comment by george-gca** [comment]
Just tried out the changes in my personal site and run a few times.
Before:

| | Desktop | Mobile |
| --- | --- | --- |
| Before | Screenshot from 2023-07-30 19-30-34 | Screenshot from 2023-07-30 19-30-40 |
| After | Screenshot from 2023-07-30 19-39-05 | Screenshot from 2023-07-30 19-39-10 |

**Comment by george-gca** [comment]
Tried to add `bootstrap-table` to use local files, but for some reason it messes with it and I can't avoid it, even after adding it to ignore files in purgecss. Best keep it loading from web.

Before purge:

image

After purge:

image

**Review by alshedivat — APPROVED** [review]
just got a chance to read through thes changes. thanks for adding PurgeCSS and switching away from CDNs. looks good to me, I'm ok with merging it.

the only concern I have is that updating versions of the libraries will be more involved (previously, we could update fontawesome and other libraries by changing a couple of lines in `_config.yml`), but I guess better speed and more flexibility are worth this inconvenience.

**Pull request merged**
