### PR TITLE
Add option for local HTML files

### PR DESCRIPTION
**Pull request by slapcat**
Add option to link HTML local files from publications page.

### CODE REVIEW

**Review by george-gca — CHANGES_REQUESTED** [review]
Instead of pointing to a fully fledged html page with lots of images, could you point to a dummy html? This way we would only need a new simple html file instead of a lot of files to use as an example.

**Review by george-gca — CHANGES_REQUESTED** [review]
Could you just change both usages of `Relativity :` to `Relativity:`?

**Review by george-gca — APPROVED** [review]

**Comment by george-gca** [comment]
Thanks for your contribution 🎉

**Comment by slapcat** [comment]
Happy to do so, thanks for the quick responses and review!

**Pull request merged**
